//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/ActionControll.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ActionControll: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ActionControll()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ActionControll"",
    ""maps"": [
        {
            ""name"": ""MyAction"",
            ""id"": ""79944990-4875-42ae-8ff2-6bb14085715b"",
            ""actions"": [
                {
                    ""name"": ""MeshAction"",
                    ""type"": ""Button"",
                    ""id"": ""54fd1007-2de8-4c55-ae24-640571bfcf58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b3951c3c-f49c-4c99-ad0c-9a04ffba4862"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MeshAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MyAction
        m_MyAction = asset.FindActionMap("MyAction", throwIfNotFound: true);
        m_MyAction_MeshAction = m_MyAction.FindAction("MeshAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MyAction
    private readonly InputActionMap m_MyAction;
    private List<IMyActionActions> m_MyActionActionsCallbackInterfaces = new List<IMyActionActions>();
    private readonly InputAction m_MyAction_MeshAction;
    public struct MyActionActions
    {
        private @ActionControll m_Wrapper;
        public MyActionActions(@ActionControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @MeshAction => m_Wrapper.m_MyAction_MeshAction;
        public InputActionMap Get() { return m_Wrapper.m_MyAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MyActionActions set) { return set.Get(); }
        public void AddCallbacks(IMyActionActions instance)
        {
            if (instance == null || m_Wrapper.m_MyActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MyActionActionsCallbackInterfaces.Add(instance);
            @MeshAction.started += instance.OnMeshAction;
            @MeshAction.performed += instance.OnMeshAction;
            @MeshAction.canceled += instance.OnMeshAction;
        }

        private void UnregisterCallbacks(IMyActionActions instance)
        {
            @MeshAction.started -= instance.OnMeshAction;
            @MeshAction.performed -= instance.OnMeshAction;
            @MeshAction.canceled -= instance.OnMeshAction;
        }

        public void RemoveCallbacks(IMyActionActions instance)
        {
            if (m_Wrapper.m_MyActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMyActionActions instance)
        {
            foreach (var item in m_Wrapper.m_MyActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MyActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MyActionActions @MyAction => new MyActionActions(this);
    public interface IMyActionActions
    {
        void OnMeshAction(InputAction.CallbackContext context);
    }
}
