//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CharacterContr.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterContr: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterContr()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterContr"",
    ""maps"": [
        {
            ""name"": ""CharacterMap"",
            ""id"": ""a769c16b-dec7-42d8-a8e6-cb6cce45ea13"",
            ""actions"": [
                {
                    ""name"": ""SetDestination"",
                    ""type"": ""Button"",
                    ""id"": ""ae391cf9-f84c-4c95-a6cb-acc73e55d940"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""548cab52-bf03-40f3-b5be-665111f00536"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SetDestination"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterMap
        m_CharacterMap = asset.FindActionMap("CharacterMap", throwIfNotFound: true);
        m_CharacterMap_SetDestination = m_CharacterMap.FindAction("SetDestination", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterMap
    private readonly InputActionMap m_CharacterMap;
    private List<ICharacterMapActions> m_CharacterMapActionsCallbackInterfaces = new List<ICharacterMapActions>();
    private readonly InputAction m_CharacterMap_SetDestination;
    public struct CharacterMapActions
    {
        private @CharacterContr m_Wrapper;
        public CharacterMapActions(@CharacterContr wrapper) { m_Wrapper = wrapper; }
        public InputAction @SetDestination => m_Wrapper.m_CharacterMap_SetDestination;
        public InputActionMap Get() { return m_Wrapper.m_CharacterMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterMapActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterMapActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Add(instance);
            @SetDestination.started += instance.OnSetDestination;
            @SetDestination.performed += instance.OnSetDestination;
            @SetDestination.canceled += instance.OnSetDestination;
        }

        private void UnregisterCallbacks(ICharacterMapActions instance)
        {
            @SetDestination.started -= instance.OnSetDestination;
            @SetDestination.performed -= instance.OnSetDestination;
            @SetDestination.canceled -= instance.OnSetDestination;
        }

        public void RemoveCallbacks(ICharacterMapActions instance)
        {
            if (m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterMapActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterMapActions @CharacterMap => new CharacterMapActions(this);
    public interface ICharacterMapActions
    {
        void OnSetDestination(InputAction.CallbackContext context);
    }
}
